

<ul class="nav">  
	<li><span class="mobile-open">Menu</span></li>
</ul> 


<nav id="navigation" data-cmsadmin-layout-nav="true">				
	<$globalmenu cssClass="main-nav" showLevels="1,2,3" alwaysShowChildren="false" showHome="true"/$>	
	
	<$shoppingcartstatus$> 
		<$cartfull$>    
			<a href="[cart.url]" class="cart">Cart <span>[cart.item_total]</span></a>
		<$/cartfull$>
		<$cartempty$><$/cartempty$>     
	<$/shoppingcartstatus$> 
</nav>


<header id="header" data-cmsadmin-layout-header="true">		
	<h1 class="logo"><a href="/"><$logo$><$websitename/$><$/logo$></a></h1>
</header>


<div class="overlay"></div>


 
